### PR TITLE
Fixed Nested childs

### LINKED ISSUE #167: Can't create more than one nested child
### Steps to reproduce
1. Run https://github.com/StarcounterApps/KitchenSink/commit/d42dba70007a1be2fe7987de6460910967232e3c (current latest version on develop)
2. Go to `http://localhost:8080/KitchenSink/Nested`
3. Click "Add child"
3. Within the child, click again "Add child"

### Expected result

nested1

### Actual result

nested2

### Technical information
It doesn't work starting with SC 2.3.1.7034 (22 aug. 2017). So it works with SC 2.3.1.7018 (18 august 2017). Couldn't find any version in between those two.

@tomalec : I'm not sure if you're the right person to tag here, but could you please have a look if you are ?

### PR DESCRIPTION
**Pull request by un-tone**
Fixed #167

### CODE REVIEW

**Comment by Mihaiii** [comment]
11 new tests are failing (only 2 on `develop`).

**Comment by un-tone** [comment]
I fixed test for Nested page. But about others it seems that there are some issues with Firefox

**Comment by un-tone** [comment]
On my computer only 2 tests are failing (DatepickerPage_SelectDate) in `fix-nested-childs` as same as in `develop`. By the way there was a lot failings with new version (56) of Firefox. I had to downgrade it to 55 version.

**Comment by Mihaiii** [comment]
I saw the log in teamcity, I'm ok with those failing tests (shouldn't be related with this PR).
Is something else that bothers me. Give me a sec, please.

**Comment by un-tone** [comment]
I have reran tests in TC. Currently there are 2 failing tests too.

**Comment by Mihaiii** [comment]
I'm sure that this PR is in accordance with what is desired.
My only problem is that this is `KitchenSink` - a repo that is shown to the new users when they first try Starcounter and with this PR the styles won't apply on the children (is there some discussion on github about this?), ending up with a strange result from a visual point of view. 

I gladly accepted your review requests in the past, but in this case, on one hand this is probably the desired solution, on another hand the CSS problem really bothers me so I have to ask you to request a review from someone else.

**Comment by un-tone** [comment]
Oh, I see the problem, I'll try to fix it

**Comment by un-tone** [comment]
Created another PR #177

**Comment by warpech** [comment]
https://github.com/StarcounterApps/KitchenSink/pull/177 is the advised way to fix this.

**Pull request closed without merging**
