### PR TITLE
Replace "paper-menu" with "paper-listbox"

### PR DESCRIPTION
**Pull request by Mihaiii**
Replace `paper-menu` with `paper-listbox` for Issue #153 .
Used version for `paper-listbox`: 1.1.3. .
Please note that the demo file for `paper-dialog` has a reference to `paper-menu`. Didn't change it since that is the way it will come at `bower install`.

### CODE REVIEW

**Comment by warpech** [comment]
Can you pls update `paper-dialog` as well then? Also, pls try current version of `paper-listbox`.

The tests are failing, probably some CSS or XPath selector needs to be changed.

**Comment by Mihaiii** [comment]
I have updated `paper-dialog` to v2.0.0. Tested it, everything is ok. I also had tested the first changes before pushing them and everything was ok there also. The failing check was because of a timeout.

**Comment by Mihaiii** [comment]
Who could review this?

**Comment by warpech** [comment]
Me :)

**Comment by warpech** [comment]
Looks great! Please merge and I will merge this to PR #151

**Pull request merged**
